import type { Store } from "./types";

export const today = new Date().toISOString().slice(0, 10);
export const accountsRegistryKey = "wedstudio-os-accounts-v1";

export const seed: Store = {
  clients: [
    {
      id: "client-1",
      createdBy: "",
      name: "Aarav & Simran",
      phone: "9800000001",
      projectType: "Wedding film",
      eventDate: "2026-06-12",
      createdAt: "2026-03-18",
      location: "Kathmandu",
      packageAmount: 18000000,
      paidAmount: 7500000,
      paymentStatus: "Unpaid",
      assignedStaff: "Studio Director",
      status: "Booked",
      notes: "Two-day wedding coverage with teaser and full film.",
    },
    {
      id: "client-2",
      createdBy: "",
      name: "Himalayan Events",
      phone: "9800000002",
      projectType: "Corporate video",
      eventDate: "2026-05-28",
      createdAt: "2026-04-05",
      location: "Lalitpur",
      packageAmount: 9500000,
      paidAmount: 9500000,
      paymentStatus: "Paid",
      assignedStaff: "Lead Editor",
      status: "Editing",
      notes: "Deliver social cuts and main highlight.",
    },
    {
      id: "client-3",
      createdBy: "",
      name: "Priya & Rohan",
      phone: "9800000003",
      projectType: "Pre-wedding shoot",
      eventDate: "2026-07-08",
      createdAt: "2026-02-10",
      location: "Pokhara",
      packageAmount: 12000000,
      paidAmount: 4000000,
      paymentStatus: "Unpaid",
      assignedStaff: "Cinematographer",
      status: "Booked",
      notes: "Lake-side pre-wedding with drone coverage.",
    },
    {
      id: "client-4",
      createdBy: "",
      name: "Everest Hospitality",
      phone: "9800000004",
      projectType: "Corporate video",
      eventDate: "2026-08-15",
      createdAt: "2026-01-22",
      location: "Bhaktapur",
      packageAmount: 6500000,
      paidAmount: 6500000,
      paymentStatus: "Paid",
      assignedStaff: "Lead Editor",
      status: "Inquiry",
      notes: "Brand film for new hotel launch.",
    },
    {
      id: "client-5",
      createdBy: "",
      name: "Anisha Gurung",
      phone: "9800000005",
      projectType: "Music video",
      eventDate: "2026-05-20",
      createdAt: "2026-05-01",
      location: "Kathmandu",
      packageAmount: 4500000,
      paidAmount: 2000000,
      paymentStatus: "Unpaid",
      assignedStaff: "Studio Director",
      status: "Editing",
      notes: "Single-day music video with color grade.",
    },
  ],
  expenses: [
    {
      id: "expense-1",
      createdBy: "",
      date: today,
      category: "Travel",
      vendor: "Fuel and parking",
      amount: 650000,
      notes: "Pre-production meeting and location scout.",
    },
    {
      id: "expense-2",
      createdBy: "",
      date: today,
      category: "Equipment",
      vendor: "Camera service",
      amount: 1250000,
      notes: "Lens calibration and sensor cleaning.",
    },
  ],
  staff: [
    {
      id: "staff-1",
      createdBy: "",
      name: "Studio Director",
      role: "Owner / Director",
      monthlySalary: 7500000,
      advance: 0,
      deduction: 0,
      status: "Pending",
    },
    {
      id: "staff-2",
      createdBy: "",
      name: "Lead Editor",
      role: "Editor",
      monthlySalary: 4200000,
      advance: 800000,
      deduction: 0,
      status: "Pending",
    },
    {
      id: "staff-3",
      createdBy: "",
      name: "Cinematographer",
      role: "Cinematographer",
      monthlySalary: 5000000,
      advance: 0,
      deduction: 300000,
      status: "Paid",
    },
  ],
  inventory: [
    {
      id: "item-1",
      createdBy: "",
      name: "Sony FX3",
      category: "Camera",
      serial: "FX3-ST-001",
      condition: "Excellent",
      dayRate: 900000,
      status: "Rented",
    },
    {
      id: "item-2",
      createdBy: "",
      name: "Sigma 24-70mm f/2.8",
      category: "Lens",
      serial: "SIG-2470-004",
      condition: "Good",
      dayRate: 350000,
      status: "Available",
    },
    {
      id: "item-3",
      createdBy: "",
      name: "DJI Ronin RS3 Pro",
      category: "Stabilizer",
      serial: "RS3-009",
      condition: "Good",
      dayRate: 250000,
      status: "Available",
    },
  ],
  rentals: [
    {
      id: "rental-1",
      createdBy: "",
      renter: "Kantipur Films",
      phone: "9811111111",
      itemId: "item-1",
      startDate: "2026-05-10",
      endDate: "2026-05-18",
      deposit: 2000000,
      amount: 2700000,
      paidAmount: 1500000,
      status: "Out",
      returnCondition: "",
    },
  ],
  bills: [],
};

export const nav: { view: import("./types").View; label: string; ownerOnly?: boolean }[] = [
  { view: "dashboard", label: "Dashboard" },
  { view: "profile", label: "Profile" },
  { view: "clients", label: "Clients" },
  { view: "bills", label: "Bills" },
  { view: "rentals", label: "Rentals" },
  { view: "inventory", label: "Inventory" },
  { view: "expenses", label: "Expenses" },
  { view: "salary", label: "Payroll" },
  { view: "reports", label: "Reports", ownerOnly: true },
];
